name: "Docker compose development"
services:
    api:
      container_name: home_api
      build:
          context: .
          dockerfile: Dockerfile
      ports:
      - "3000:3000"
      depends_on:
        - db
      env_file: .env
    cache:
        container_name: home_cache
        image: redis/redis-stack:7.4.0-v1
        ports:
        - "6379:6379"
        - "8001:8001"
        volumes:
          - cache_date:/data
    db:
      container_name: home_postgres
      image: postgres:16.4
      ports:
      - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
      - POSTGRES_USER=home_usr
      - POSTGRES_PASSWORD=home_password
      - POSTGRES_DB=home_db


volumes:
  db_data:
  cache_date: