name: "Docker compose development"
services:
    api:
      container_name: kardinal_api
      build:
          context: .
          dockerfile: Dockerfile
      ports:
      - "3000:3000"
      depends_on:
        - db_migration
      env_file: .env
      restart: always
    cache:
        container_name: kardinal_cache
        image: redis/redis-stack-server:7.4.0-v1
        ports:
        - "6379:6379"
        volumes:
          - cache_date:/data
        environment:
          - REDIS_ARGS="--requirepass ${REDIS_PASSWORD}"
    db:
      container_name: kardinal_db
      image: postgres:16.4
      ports:
      - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    db_migration:
      container_name: kardinal_db_migration
      build:
          context: migration
          dockerfile: Dockerfile
      depends_on:
        - db
      environment:
        - DATABASE_URL=${DATABASE_URL}
volumes:
  db_data:
  cache_date: