name: "Build & Test"

on:
  push:
    branches:
      - "main"
      - "alpha"
      - "beta"
      - "next"
jobs:
  build_api:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        shell: bash
        run: |
          cargo +stable --version
          rustc +stable --version
      - name: "Cargo check, test and build"
        run: |
            cargo check --all
            cargo test --all
            cargo build --release