name: "Build docker image with tag"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: kardinal_api
            context: .
          - dockerfile: ./migration/Dockerfile
            image: kardinal_migration
            context: ./migration
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
      - name: "Build and push"
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: 'Webhook to deploy Api service'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_DEPLOY_WEBHOOK }}
      - name: 'Webhook to deploy Migration service'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.MIGRATION_DEPLOY_WEBHOOK }}