//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod house;
pub mod house_user;
pub mod password;
pub mod permission;
pub mod role;
pub mod role_permission;
pub mod sea_orm_active_enums;
pub mod settings;
pub mod user;
pub mod user_role;
