//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use super::sea_orm_active_enums::NoteType;
use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "note")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub content: Json,
    pub description: Option<String>,
    pub r#type: NoteType,
    pub created_at: DateTime,
    pub created_by: Option<String>,
    pub updated_at: Option<DateTime>,
    pub archived_by: Option<String>,
    pub archived_at: Option<DateTime>,
    pub updated_by: Option<String>,
    pub deleted_at: Option<DateTime>,
    pub deleted_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::house_note::Entity")]
    HouseNote,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ArchivedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User4,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User3,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::DeletedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::house_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HouseNote.def()
    }
}

impl Related<super::house::Entity> for Entity {
    fn to() -> RelationDef {
        super::house_note::Relation::House.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::house_note::Relation::Note.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
