//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "credentials_type")]
pub enum CredentialsType {
    #[sea_orm(string_value = "application")]
    Application,
    #[sea_orm(string_value = "bank_account")]
    BankAccount,
    #[sea_orm(string_value = "cloud_storage")]
    CloudStorage,
    #[sea_orm(string_value = "database")]
    Database,
    #[sea_orm(string_value = "device")]
    Device,
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "other")]
    Other,
    #[sea_orm(string_value = "streaming_service")]
    StreamingService,
    #[sea_orm(string_value = "website")]
    Website,
    #[sea_orm(string_value = "wifi")]
    Wifi,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "house_location_type"
)]
pub enum HouseLocationType {
    #[sea_orm(string_value = "owned")]
    Owned,
    #[sea_orm(string_value = "rented")]
    Rented,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "house_user_status")]
pub enum HouseUserStatus {
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "declined")]
    Declined,
    #[sea_orm(string_value = "pending")]
    Pending,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "registered_with")]
pub enum RegisteredWith {
    #[sea_orm(string_value = "apple")]
    Apple,
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "native")]
    Native,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "settings_type")]
pub enum SettingsType {
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "boolean_array")]
    BooleanArray,
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "secret")]
    Secret,
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "string_array")]
    StringArray,
}
