//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub is_active: bool,
    pub is_deleted: bool,
    pub phone_number: Option<String>,
    pub birthday: Option<Date>,
    pub country: Option<String>,
    pub city: Option<String>,
    pub address: Option<String>,
    pub zip_code: Option<String>,
    pub created_at: DateTime,
    pub created_by: Option<Uuid>,
    pub updated_at: Option<DateTime>,
    pub updated_by: Option<Uuid>,
    pub deleted_at: Option<DateTime>,
    pub deleted_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub picture: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CreatedBy",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef3,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::DeletedBy",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::UpdatedBy",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef1,
}

impl ActiveModelBehavior for ActiveModel {}
